const GSBDD_LIST = [
  'Angers - Le Mans - Saumur',
  'Angoulême',
  'Belfort',
  'Besancon',
  'Bordeaux-Mérignac',
  'Bourges-Avord',
  'Brest - Lorient',
  'Brive-la-Gaillarde',
  'Charleville-Mézières',
  'Calvi',
  'Carcassonne',
  'Cazaux',
  'Cherbourg',
  'Clermont-Ferrand',
  'Colmar',
  'Creil',
  'Draguignan',
  'Epinal-Luxeuil',
  'Evreux',
  'Gap',
  'Grenoble - Annecy - Chambery',
  'Istres - Orange - Salon de Provence',
  'La Valbonne',
  'Lille',
  'Lyon Mont-Verdun',
  'Marseille Aubagne',
  'Metz',
  'Mont-de-Marsan',
  'Montauban ',
  'Monthléry',
  'Mourmelon Mailly',
  'Nancy',
  'Nîmes Laudun Larzac',
  'Orleans - Bricy',
  'Paris - St Germain en Laye',
  'Paris - Versailles',
  'Paris - Villacoublay',
  'Paris - Vincennes',
  'Paris-Ecole militaire',
  'Pau - Bayonne',
  'Phalsbourg',
  'Poitiers - St-Maixent',
  'Rennes',
  'Rochefort-Cognac',
  'Saint-Christol',
  'Saint-Dizier - Chaumont',
  'Strasbourg - Haguenau',
  'Toulon',
  'Toulouse Tarbes Castres',
  'Tours',
  'Valence',
  'Vannes - Coetquidan',
  'Ventiseri-Solenzara',
  'Verdun',
];

export const state = () => ({ list: GSBDD_LIST });

export const mutations = {};
